# Generated by Django 5.2.15 on 2026-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("severity", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=20)),
                ("metric", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("condition", models.CharField(max_length=200)),
                ("channels", models.CharField(max_length=120)),
                ("on", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("who", models.CharField(max_length=120)),
                ("initials", models.CharField(max_length=4)),
                ("color", models.CharField(max_length=20)),
                ("action", models.CharField(max_length=200)),
                ("target", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Crisis",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=20)),
                ("severity", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
                ("opened", models.CharField(max_length=40)),
                ("owner", models.CharField(max_length=120)),
                ("summary", models.TextField()),
                ("signals", models.JSONField(default=list)),
                ("timeline", models.JSONField(default=list)),
                ("strategies", models.JSONField(default=list)),
                ("war_room", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "crises",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("handle", models.CharField(max_length=120)),
                ("platform", models.CharField(max_length=20)),
                ("followers", models.CharField(max_length=20)),
                ("reach", models.CharField(max_length=20)),
                ("sentiment", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("account", models.CharField(max_length=120)),
                ("status", models.CharField(max_length=20)),
                ("detail", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("platform", models.CharField(max_length=20)),
                ("author_name", models.CharField(max_length=120)),
                ("author_handle", models.CharField(max_length=120)),
                (
                    "author_avatar",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("author_initials", models.CharField(max_length=4)),
                ("author_color", models.CharField(max_length=20)),
                ("author_followers", models.CharField(max_length=40)),
                ("author_verified", models.BooleanField(default=False)),
                ("content", models.TextField()),
                ("time", models.CharField(max_length=20)),
                ("sentiment", models.CharField(max_length=20)),
                ("priority", models.CharField(max_length=20)),
                ("reach", models.CharField(max_length=20)),
                ("likes", models.CharField(max_length=20)),
                ("comments", models.CharField(max_length=20)),
                ("shares", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=60)),
                ("status", models.CharField(max_length=20)),
                ("assignee", models.CharField(blank=True, max_length=120, null=True)),
                ("confidence", models.IntegerField()),
                ("emotions", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                ("suggested_reply", models.TextField()),
                ("notes", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=20)),
                ("period", models.CharField(max_length=60)),
                ("generated", models.CharField(max_length=60)),
                ("status", models.CharField(max_length=20)),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TeamUser",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("initials", models.CharField(max_length=4)),
                ("color", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("last_active", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
