# Generated by Django 5.2.15 on 2026-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("freq", models.CharField(max_length=60)),
                ("recipients", models.CharField(max_length=120)),
                ("on", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
