# Generated by Django 5.2.17 on 2026-10-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_teamuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('text', models.TextField()),
                ('sentiment', models.CharField(db_index=True, max_length=20)),
                ('hashtags', models.JSONField(default=list)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement', models.PositiveIntegerField(default=0)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
